apiVersion: v1
kind: Service 
metadata:
  name: sys-info
spec: 
  selector:
    app-type: web-server
  ports:
    - protocol: TCP 
      port: 8080
      targetPort: 3000
      nodePort: 30100
  type: NodePort 