apiVersion: v1
kind: Pod 
metadata:
  name: sys-info-server
  labels:
    app-type: web-server
spec:
  containers:
    - name: node-sys-info
      image: rockink/node-sys-info:v2
      ports:
        - containerPort: 3000